// <auto-generated />
namespace eService.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RefactorDBconstraints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RefactorDBconstraints));
        
        string IMigrationMetadata.Id
        {
            get { return "201802041412374_Refactor DB constraints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
